# Generated by Django 5.0.6 on 2024-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='C:/Users/kayra/socialmediaproject/static/img'),
        ),
    ]
